---
- name: Deploy relay
  hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars:
    relay_web_repo: https://github.com/tessercat/relay-web.git
    relay_web_version: dev
    relay_ws_port: 8910
    relay_ejabberd_version: 21.12
    relay_ejabberd_rev: 0
  roles:
    - {role: web, tags: [web]}
    - {role: ejabberd, tags: [ejabberd]}
