---

- name: Restart relay service
  listen:
    - restart relay service
  ansible.builtin.systemd:
    name: relay.service
    state: restarted

- name: Restart nginx service
  listen:
    - restart relay nginx service
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
