---
# OS.

- name: User
  ansible.builtin.user:
    name: relay
    system: true
    shell: /usr/sbin/nologin

- name: Relay directory
  ansible.builtin.file:
    path: /opt/relay
    state: directory
    mode: 0755

- name: Deno directory
  ansible.builtin.file:
    path: /opt/relay/deno
    state: directory
    mode: 0700
    owner: relay
    group: relay

- name: Deno bin directory
  ansible.builtin.file:
    path: /opt/relay/deno/bin
    state: directory
    mode: 0755
    owner: relay
    group: relay


# Download and install deno.

- name: Stat archive
  ansible.builtin.stat:
    path: "/opt/relay/deno/\
           deno-{{ relay_deno_version }}-x86_64-unknown-linux-gnu.zip"
  register: deno_archive
  # Download

- name: Download
  ansible.builtin.get_url:
    url: "https://github.com/denoland/deno/releases/download/\
          v{{ relay_deno_version }}/\
          deno-x86_64-unknown-linux-gnu.zip"
    dest: "/opt/relay/deno/\
           deno-{{ relay_deno_version }}-x86_64-unknown-linux-gnu.zip"
    mode: 0644
  when: not deno_archive.stat.exists
  register: deno_download
  # Clean

- name: Clean
  ansible.builtin.file:
    path: /opt/relay/deno/bin/deno
    state: absent
  when: deno_download is changed

- name: Unarchive
  ansible.builtin.unarchive:
    src: "/opt/relay/deno/\
          deno-{{ relay_deno_version }}-x86_64-unknown-linux-gnu.zip"
    dest: /opt/relay/deno/bin
    remote_src: true
    owner: relay
    group: relay
  when: deno_download is changed

- name: Chmod
  ansible.builtin.file:
    path: /opt/relay/deno/bin/deno
    mode: 0700
