---

- name: User
  ansible.builtin.user:
    name: relay
    system: true
    shell: /usr/sbin/nologin

- name: Relay directory
  ansible.builtin.file:
    path: /opt/relay
    state: directory
    mode: 0755

- name: Web directory
  ansible.builtin.file:
    path: /opt/relay/web
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- name: Repo
  become: true
  become_user: www-data
  ansible.builtin.git:
    repo: "{{ relay_web_repo }}"
    dest: /opt/relay/web
    version: "{{ relay_web_version }}"
    force: true

- name: Nginx
  notify:
    - restart relay nginx service
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/relay.conf
    mode: 0644


# Handlers.

- name: Handlers
  ansible.builtin.meta: flush_handlers
